# Generated by Django 4.1.2 on 2022-11-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_ordenservicio_ord_s_email_cli_and_more'),
        ('articulos', '0008_rename_artestado_articulos_art_estado'),
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_lugar_emision', models.CharField(max_length=50, verbose_name='Lugar de emisión:')),
                ('ord_direccion', models.CharField(max_length=80, verbose_name='Dirección:')),
                ('ord_fecha', models.DateField(verbose_name='Fecha:')),
                ('ord_termino_pago', models.CharField(choices=[('Pago de contado con efectivo', 'Pago de contado con efectivo'), ('Pago de contado con tarjeta', 'Pago de contado con tarjeta'), ('A crédito', 'A crédito'), ('Pago anticipado con efectivo', 'Pago anticipado con efectivo'), ('Pago anticipado con tarjeta', 'Pago anticipado con tarjeta'), ('Otro', 'Otro')], max_length=28, verbose_name='Término de pago:')),
                ('ord_metodo_entrega', models.CharField(choices=[('Domicilio', 'Domicilio'), ('Entrega persononal', 'Entrega personal'), ('Otro', 'Otro')], max_length=18, verbose_name='Término de entrega para el pedido')),
                ('ord_otras_tarifas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Otras tarifas:')),
                ('ord_costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo total estimado:')),
                ('ord_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
                ('ord_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleados', verbose_name='Empleado responsable:')),
                ('ord_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.proveedores', verbose_name='Proveedor:')),
                ('tbl_cotizaciones_idcotizacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='herramientas.cotizacionescompras', verbose_name='Cotización:')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ped_recivido_por', models.CharField(max_length=80, verbose_name='Recivido por:')),
                ('ped_fecha_recivido', models.DateField(verbose_name='Fecha de recivido:')),
                ('ped_precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total:')),
                ('ped_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
                ('tbl_orden_compras_idorden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra', verbose_name='Órden de compra:')),
            ],
        ),
        migrations.CreateModel(
            name='TblRelPedidosArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_articulo_cantidad', models.SmallIntegerField(verbose_name='Cantidad:')),
                ('rel_precio_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio compra:')),
                ('rel_precio_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio venta:')),
                ('tbl_articulos_idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos', verbose_name='Artículo:')),
                ('tbl_pedidos_idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pedidos', verbose_name='Pedido número:')),
            ],
        ),
        migrations.CreateModel(
            name='TblRelOrdenCompraArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_cantidad', models.SmallIntegerField(verbose_name='Cantidad:')),
                ('rel_precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario:')),
                ('rel_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio total:')),
                ('tbl_articulos_idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos', verbose_name='Artículo:')),
                ('tbl_orden_compras_idorden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra', verbose_name='Órden de compra:')),
            ],
        ),
    ]
