# Generated by Django 4.1.2 on 2022-11-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='ord_metodo_entrega',
            new_name='ord_termino_entrega',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ord_celular',
            field=models.CharField(default=0, max_length=20, verbose_name='Teléfono:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ord_email',
            field=models.EmailField(default=0, max_length=100, verbose_name='Email:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ord_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono:'),
        ),
    ]
