# Generated by Django 4.1.2 on 2022-11-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_ord_metodo_entrega_ordencompra_ord_termino_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='tbl_orden_compras_idorden_compra',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra', verbose_name='Órden de compra:'),
        ),
    ]
