# Generated by Django 4.1.3 on 2022-12-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_pedidos_tbl_orden_compras_idorden_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tbl_orden_compras_idorden_compra',
        ),
    ]
