# Generated by Django 4.1.3 on 2022-12-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_pedidos_tbl_orden_compras_idorden_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrelpedidosarticulos',
            name='rel_precio_venta',
        ),
    ]
