# Generated by Django 4.1.3 on 2022-12-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_tblrelpedidosarticulos_rel_precio_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='tbl_cotizaciones_idcotizacion',
        ),
        migrations.RemoveField(
            model_name='tblrelordencompraarticulos',
            name='rel_total',
        ),
    ]
