# Generated by Django 4.1.3 on 2022-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_ordencompra_tbl_cotizaciones_idcotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='ord_costo_total',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='ord_celular',
            field=models.CharField(max_length=20, verbose_name='Celular:'),
        ),
    ]
