# Generated by Django 4.1.3 on 2022-12-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_ordencompra_ord_costo_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Cerrado')], default='1', max_length=1, verbose_name='Estado:'),
        ),
    ]
