# Generated by Django 4.1.3 on 2022-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_pedidos_ped_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='ord_estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Cerrada')], default='1', max_length=1, verbose_name='Estado:'),
        ),
    ]
