# Generated by Django 4.1.3 on 2022-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_ordencompra_ord_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='ord_otras_tarifas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Ótras tarifas:'),
        ),
    ]
