# Generated by Django 4.1.2 on 2022-11-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_ordenservicio_ord_s_email_cli_and_more'),
        ('articulos', '0008_rename_artestado_articulos_art_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionesCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot_fecha', models.DateField(verbose_name='Fecha:')),
                ('cot_costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo total:')),
                ('ord_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
                ('cot_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.proveedores', verbose_name='Proveedor:')),
                ('tbl_empleados_idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleados', verbose_name='Empleado:')),
            ],
        ),
        migrations.CreateModel(
            name='TblRelCotizacionesComprasArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_cantidad', models.SmallIntegerField(verbose_name='Cantidad:')),
                ('rel_precio_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio compra:')),
                ('rel_precio_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio venta:')),
                ('rel_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio total:')),
                ('tbl_articulos_idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos', verbose_name='Artículo:')),
                ('tbl_cotizaciones_compras_idcotizacion_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas.cotizacionescompras', verbose_name='Cotización de compra número:')),
            ],
        ),
    ]
