# Generated by Django 4.1.1 on 2022-10-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatNombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('CatDescripcion', models.TextField(max_length=100, verbose_name='Descripción:')),
                ('CatEstado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarArNombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('MarArDescripcion', models.TextField(max_length=100, verbose_name='Descripción:')),
                ('MarArEstado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProNit', models.CharField(max_length=20, verbose_name='Nit/Referencia:')),
                ('ProNombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('ProCategoria', models.CharField(max_length=50, verbose_name='Categoría:')),
                ('ProPersonaNat', models.CharField(max_length=50, verbose_name='Persona natural:')),
                ('ProDireccion', models.CharField(max_length=100, verbose_name='Dirección:')),
                ('ProTelefono', models.CharField(max_length=20, verbose_name='Teléfono:')),
                ('ProCelular', models.CharField(max_length=20, verbose_name='Celular:')),
                ('ProEmail', models.CharField(max_length=100, verbose_name='Email:')),
                ('ProSitioWeb', models.CharField(max_length=300, verbose_name='Sitio web:')),
                ('ProEstado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtNombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('ArtStockDisp', models.SmallIntegerField(verbose_name='Stock Disponible:')),
                ('ArtDescripcion', models.TextField(max_length=200, verbose_name='Descripción:')),
                ('ArtStockMinimo', models.SmallIntegerField(verbose_name='Stock mínimo:')),
                ('ArtStockMaximo', models.SmallIntegerField(verbose_name='Stock máximo:')),
                ('ArtEstado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('TblCategoria_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.categoria', verbose_name='Categoría:')),
                ('TblMarcaArticulos_idMarcaArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.marcaarticulos', verbose_name='Marca:')),
                ('TblProveedores_idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.proveedores', verbose_name='Proveedor:')),
            ],
        ),
    ]
