# Generated by Django 4.1.1 on 2022-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='ArtStockDisp',
            field=models.SmallIntegerField(blank=True, verbose_name='Stock Disponible:'),
        ),
    ]
