# Generated by Django 4.1.2 on 2022-10-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulos_artstockdisp'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='ArtFoto',
            field=models.ImageField(blank=True, default='images/articulos/default.png', upload_to='images/articulos'),
        ),
    ]
