# Generated by Django 4.1.2 on 2022-10-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulos_artfoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarcaArticulos',
            new_name='Marcas',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='TblMarcaArticulos_idMarcaArticulo',
            new_name='TblMarcas_idMarca',
        ),
        migrations.RenameField(
            model_name='marcas',
            old_name='MarArDescripcion',
            new_name='MarDescripcion',
        ),
        migrations.RenameField(
            model_name='marcas',
            old_name='MarArEstado',
            new_name='MarEstado',
        ),
        migrations.RenameField(
            model_name='marcas',
            old_name='MarArNombre',
            new_name='MarNombre',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='ArtFoto',
            field=models.ImageField(blank=True, default='images/articulos/default.png', upload_to='images/articulos', verbose_name='Foto:'),
        ),
    ]
