# Generated by Django 4.1.2 on 2022-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_rename_marcaarticulos_marcas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='MarDescripcion',
            field=models.TextField(max_length=200, verbose_name='Descripción:'),
        ),
    ]
