# Generated by Django 4.1.2 on 2022-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_marcas_mardescripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='ArtStockDisp',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Stock Disponible:'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='ProEmail',
            field=models.EmailField(max_length=100, verbose_name='Email:'),
        ),
    ]
