# Generated by Django 4.1.2 on 2022-11-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_rename_artdescripcion_articulos_art_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='ArtEstado',
            new_name='art_estado',
        ),
    ]
