# Generated by Django 4.1.3 on 2022-12-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_articulos_art_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='art_stock_disp',
        ),
    ]
