# Generated by Django 4.1.3 on 2022-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_remove_articulos_art_stock_disp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='art_foto',
            field=models.ImageField(blank=True, default='images/articulos/default.png', upload_to='images/articulos/', verbose_name='Foto:'),
        ),
    ]
