# Generated by Django 4.1.2 on 2022-11-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0008_rename_artestado_articulos_art_estado'),
        ('usuarios', '0008_empleados_user'),
        ('facturacion', '0002_remove_facturaventa_tbl_clientes_idcliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('fac_numero_serie', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de serie:')),
                ('fac_fecha', models.DateField(auto_now=True, verbose_name='Fecha:')),
                ('fac_caja', models.DateField(max_length=10, verbose_name='Caja número:')),
                ('fac_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Descuento:')),
                ('fac_total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total a pagar:')),
                ('fac_observaciones', models.TextField(max_length=350, verbose_name='Observaciones:')),
                ('fac_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
                ('tbl_clientes_idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente:')),
                ('tbl_empleados_idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleados', verbose_name='Empleado:')),
                ('tbl_ordenes_servicio_idorden_servicio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ordenservicio', verbose_name='Órden de servicio número:')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio:')),
                ('dep_cantidad', models.SmallIntegerField(verbose_name='Cantidad:')),
                ('dep_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
                ('tbl_articulos_idarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos', verbose_name='Artículos:')),
                ('tbl_facturas_idfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturaventa', verbose_name='Factura número:')),
            ],
        ),
    ]
