# Generated by Django 4.1.2 on 2022-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='fac_caja',
            field=models.CharField(max_length=10, verbose_name='Caja número:'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='fac_fecha',
            field=models.DateField(verbose_name='Fecha:'),
        ),
    ]
