# Generated by Django 4.1.2 on 2022-11-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_rename_artestado_articulos_art_estado'),
        ('facturacion', '0004_alter_facturaventa_fac_caja_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleFactura',
            new_name='DetalleFacturaVenta',
        ),
    ]
