# Generated by Django 4.1.3 on 2022-11-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_rename_detallefactura_detallefacturaventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='fac_fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha:'),
        ),
    ]
