# Generated by Django 4.1.3 on 2022-12-02 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_empresa_empr_foto'),
        ('facturacion', '0006_alter_facturaventa_fac_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='tbl_ordenes_servicio_idorden_servicio',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ordenservicio', verbose_name='Órden de servicio número:'),
        ),
    ]
