# Generated by Django 4.1.3 on 2022-12-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_facturaventa_tbl_ordenes_servicio_idorden_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefacturaventa',
            name='dep_estado',
        ),
    ]
