# Generated by Django 4.1.3 on 2022-12-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_remove_detallefacturaventa_dep_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventa',
            name='fac_total_pagar',
        ),
    ]
