# Generated by Django 4.1.3 on 2022-12-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_facturaventa_tbl_ordenes_servicio_idorden_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='fac_estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Cerrada')], default='1', max_length=1, verbose_name='Estado:'),
        ),
    ]
