# Generated by Django 4.1.3 on 2022-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_facturaventa_fac_costo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='fac_numero_serie',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Número de serie:'),
        ),
    ]
