# Generated by Django 4.1.2 on 2022-11-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciudad', models.CharField(max_length=10, verbose_name='Código nacional_')),
                ('ciu_nombre', models.CharField(max_length=45, verbose_name='Nombre:')),
                ('ciu_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_depart', models.CharField(max_length=10, verbose_name='Código nacional:')),
                ('dep_nombre', models.CharField(max_length=45, verbose_name='Nombre_')),
                ('dep_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_identificacion', models.CharField(max_length=50, verbose_name='Identificación:')),
                ('cli_tipo_documento', models.CharField(choices=[('T.I', 'Tarjeta de Identidad'), ('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('Pas', 'Pasaporte')], default='C.C', max_length=3, verbose_name='Tipo de documento:')),
                ('cli_nombres', models.CharField(max_length=50, verbose_name='Nombres:')),
                ('cli_apellidos', models.CharField(max_length=50, verbose_name='Apellidos:')),
                ('cli_genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Maculino')], max_length=2)),
                ('cli_direccion', models.CharField(max_length=100, verbose_name='Dirección:')),
                ('cli_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono:')),
                ('cli_celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('cli_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('cli_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('tbl_ciudades_idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudades', verbose_name='Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='tbl_departamento_iddepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamentos', verbose_name='Departamento:'),
        ),
    ]
