# Generated by Django 4.1.2 on 2022-11-01 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_rename_artestado_articulos_art_estado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp_identificacion', models.CharField(max_length=50, verbose_name='Identificación:')),
                ('emp_tipo_documento', models.CharField(choices=[('T.I', 'Tarjeta de Identidad'), ('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('Pas', 'Pasaporte')], default='C.C', max_length=3, verbose_name='Tipo de documento:')),
                ('emp_nombre', models.CharField(max_length=50, verbose_name='Nombres:')),
                ('emp_apellidos', models.CharField(max_length=50, verbose_name='Apellidos:')),
                ('emp_genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Maculino')], max_length=1, verbose_name='Genero:')),
                ('emp_direccion', models.CharField(max_length=100, verbose_name='Dirección:')),
                ('emp_telefono', models.CharField(max_length=20, verbose_name='Teléfono:')),
                ('emp_celular', models.CharField(max_length=20, verbose_name='Celular:')),
                ('emp_email', models.CharField(max_length=100, verbose_name='E-mail:')),
                ('emp_fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento:')),
                ('emp_cargo', models.CharField(max_length=50, verbose_name='Cargo:')),
                ('emp_num_contrato', models.CharField(max_length=50, verbose_name='Número de Contrato:')),
                ('emp_fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso:')),
                ('emp_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('emp_foto', models.ImageField(blank=True, default='images/empleados_usuarios/default.png', upload_to='images/empleados_usuarios', verbose_name='Foto:')),
                ('tbl_ciudad_idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudades', verbose_name='Ciudades:')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empr_nombre', models.CharField(max_length=80, verbose_name='Nombre:')),
                ('empr_nit', models.CharField(max_length=20, verbose_name='Nit:')),
                ('empr_dueno', models.CharField(max_length=80, verbose_name='Dueño:')),
                ('empr_sitio_web', models.CharField(max_length=100, verbose_name='Sitio Web:')),
                ('empr_razon_social', models.CharField(max_length=120, verbose_name='Razon Social:')),
                ('empr_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_s_identificacion_responsable', models.CharField(max_length=20, verbose_name='Identificación:')),
                ('ord_s_fecha', models.DateField(verbose_name='Fecha:')),
                ('ord_s_telefono_responsable', models.CharField(blank=True, max_length=20, verbose_name='Teléfono:')),
                ('ord_s_celular_resposable', models.CharField(max_length=20, verbose_name='Celular:')),
                ('ord_s_direccion_responsable', models.CharField(max_length=100, verbose_name='Dirección:')),
                ('ord_s_fecha_entrega', models.DateField(verbose_name='Entrega:')),
                ('ord_s_identificacion_cli', models.CharField(max_length=20, verbose_name='Identificación:')),
                ('ord_s_telefono_cli', models.CharField(blank=True, max_length=20, verbose_name='Teléfono:')),
                ('ord_s_celular_cli', models.CharField(max_length=20, verbose_name='Celular:')),
                ('ord_s_direccion_cli', models.CharField(blank=True, max_length=100, verbose_name='Dirección:')),
                ('ord_s_vehiculo', models.CharField(max_length=6, verbose_name='Vehículo:')),
                ('ord_s_informe_tecnico', models.TextField(max_length=300, verbose_name='Informe técnico:')),
                ('ord_s_estado_pago', models.CharField(choices=[('1', 'Pagado'), ('0', 'Sin pagar')], default='1', max_length=1, verbose_name='Estado de pago')),
                ('ser_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('ser_descripcion', models.TextField(max_length=200, verbose_name='Descripción:')),
                ('ser_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Maculino')], max_length=2, verbose_name='Genero:'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matricula', models.CharField(max_length=6, verbose_name='Matrícula:')),
                ('veh_modelo', models.CharField(max_length=45, verbose_name='Modelo:')),
                ('veh_color', models.CharField(max_length=20, verbose_name='Color:')),
                ('veh_version', models.CharField(max_length=20, verbose_name='Versión_')),
                ('veh_anio', models.CharField(max_length=4, verbose_name='Año:')),
                ('veh_chasis_vin', models.CharField(max_length=45, verbose_name='Chasis_VIN:')),
                ('veh_motor', models.CharField(max_length=45, verbose_name='Motor:')),
                ('veh_ultima_fecha_ingreso', models.DateField(verbose_name='Ultima fecha de ingreso:')),
                ('veh_ultima_fecha_salida', models.DateField(verbose_name='Ultima fecha de salida:')),
                ('veh_informe_tecnico', models.TextField(max_length=200, verbose_name='Informe técnico:')),
                ('veh_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('veh_taller', models.CharField(choices=[('Si', 'En taller'), ('No', 'Entregado')], default='Si', max_length=2, verbose_name='Proceso:')),
                ('tbl_cliente_ididentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Dueño:')),
                ('tbl_marcas_idmarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.marcas', verbose_name='Marca:')),
            ],
        ),
        migrations.CreateModel(
            name='TblRelServiciosEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_empleados_idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleados', verbose_name='Empleado:')),
                ('tbl_servicios_idservicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.servicios', verbose_name='Servicios:')),
            ],
        ),
        migrations.CreateModel(
            name='TblRelOrdenServicioArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_cantidad', models.SmallIntegerField(blank=True, verbose_name='Cantidad:')),
                ('art_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Precio:')),
                ('Ttbl_articulos_idarticulo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos', verbose_name='Artículos:')),
                ('tbl_orden_servicio_idorden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ordenservicio', verbose_name='Orden de servicio:')),
            ],
        ),
        migrations.CreateModel(
            name='TblRelClienteServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_cliente_ididentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente:')),
                ('tbl_servicios_idservicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.servicios', verbose_name='Servicio:')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suc_nombre', models.CharField(max_length=80, verbose_name='Nombre:')),
                ('suc_administrador', models.CharField(max_length=80, verbose_name='Administrador:')),
                ('suc_direccion', models.CharField(max_length=80, verbose_name='Direccion:')),
                ('suc_tipo', models.CharField(choices=[('1', 'Principal'), ('0', 'Sede')], default='0', max_length=1, verbose_name='Tipo:')),
                ('suc_telefono', models.CharField(max_length=20, verbose_name='Teléfono:')),
                ('suc_celular', models.CharField(max_length=20, verbose_name='Celular:')),
                ('suc_email', models.CharField(max_length=100, verbose_name='E-mail:')),
                ('suc_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:')),
                ('tbl_ciudad_idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudades', verbose_name='Ciudades:')),
                ('tbl_empresas_idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa:')),
            ],
        ),
        migrations.AddField(
            model_name='servicios',
            name='tbl_sucursales_idsucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursales', verbose_name='Sucursal:'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tbl_clientes_idcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Nombre:'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tbl_empleados_idempleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleados', verbose_name='Nombre:'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tbl_servicos_idservicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.servicios', verbose_name='Servicio:'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tbl_sucursal_idsucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursales', verbose_name='Sucursal:'),
        ),
    ]
