# Generated by Django 4.1.2 on 2022-11-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empleados_empresa_ordenservicio_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='ord_s_email_cli',
            field=models.EmailField(default=0, max_length=100, verbose_name='Email:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='ord_s_email_responsable',
            field=models.EmailField(default=0, max_length=100, verbose_name='Email:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='ord_s_estado_pago',
            field=models.CharField(choices=[('1', 'Pagado'), ('0', 'Sin pagar')], max_length=1, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='veh_version',
            field=models.CharField(max_length=20, verbose_name='Versión:'),
        ),
    ]
