# Generated by Django 4.1.2 on 2022-11-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_ordenservicio_ord_s_email_cli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='emp_email',
            field=models.EmailField(max_length=100, verbose_name='E-mail:'),
        ),
    ]
