# Generated by Django 4.1.2 on 2022-11-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_empleados_emp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='emp_foto',
            field=models.ImageField(blank=True, default='images/usuarios/default.png', upload_to='images/usuarios', verbose_name='Foto:'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empr_razon_social',
            field=models.TextField(max_length=300, verbose_name='Razon Social:'),
        ),
    ]
