# Generated by Django 4.1.2 on 2022-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_empleados_emp_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='emp_s_mantenimiento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='empleados',
            name='emp_s_ventas',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='empleados',
            name='emp_solo_cargo',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2, verbose_name='Genero:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='emp_genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Genero:'),
        ),
    ]
