# Generated by Django 4.1.2 on 2022-11-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_empleados_emp_s_mantenimiento_empleados_emp_s_ventas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='emp_s_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='emp_s_ventas',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='emp_solo_cargo',
        ),
    ]
