# Generated by Django 4.1.2 on 2022-11-10 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_remove_empleados_emp_s_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
