# Generated by Django 4.1.2 on 2022-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_empleados_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrelordenservicioarticulos',
            name='tbl_estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado:'),
        ),
    ]
