# Generated by Django 4.1.2 on 2022-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_tblrelordenservicioarticulos_tbl_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='dep_nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre:'),
        ),
    ]
