# Generated by Django 4.1.3 on 2022-11-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_departamentos_dep_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empr_foto',
            field=models.ImageField(blank=True, default='images/empresa/default.png', upload_to='images/empresa', verbose_name='Foto:'),
        ),
    ]
