# Generated by Django 4.1.3 on 2022-12-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_empresa_empr_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenservicio',
            name='ord_s_direccion_cli',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='ord_s_email_cli',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='ord_s_telefono_cli',
        ),
    ]
