# Generated by Django 4.1.3 on 2022-12-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_ordenservicio_ord_s_celular_resposable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrelordenservicioarticulos',
            name='tbl_estado',
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='ord_s_fecha',
            field=models.DateField(verbose_name='Fecha de registro:'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='tbl_clientes_idcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente:'),
        ),
    ]
