# Generated by Django 4.1.3 on 2022-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_tblrelordenservicioarticulos_tbl_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='ord_s_estado_pago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Sin pagar', 'Sin pagar')], max_length=9, verbose_name='Estado de pago'),
        ),
    ]
