# Generated by Django 4.1.3 on 2022-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_ordenservicio_ord_s_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2, verbose_name='Género:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_identificacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identificación:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='emp_genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Género:'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empr_razon_social',
            field=models.TextField(max_length=300, verbose_name='Razón Social:'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='ord_s_informe_tecnico',
            field=models.TextField(max_length=500, verbose_name='Informe técnico:'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='suc_direccion',
            field=models.CharField(max_length=80, verbose_name='Dirección:'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='veh_informe_tecnico',
            field=models.TextField(max_length=500, verbose_name='Informe técnico:'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='veh_ultima_fecha_ingreso',
            field=models.DateField(verbose_name='Última fecha de ingreso:'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='veh_ultima_fecha_salida',
            field=models.DateField(blank=True, verbose_name='Última fecha de salida:'),
        ),
    ]
