# Generated by Django 4.1.3 on 2022-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_cliente_cli_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='id_matricula',
            field=models.CharField(max_length=6, unique=True, verbose_name='Matrícula:'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='veh_ultima_fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Última fecha de salida:'),
        ),
    ]
