# Generated by Django 4.1.3 on 2022-12-12 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_remove_articulos_art_stock_disp'),
        ('usuarios', '0017_alter_vehiculo_id_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='emp_email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_emp_identificacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identificación:'),
        ),
        migrations.AlterField(
            model_name='tblrelordenservicioarticulos',
            name='Ttbl_articulos_idarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos', verbose_name='Artículos:'),
        ),
        migrations.AlterField(
            model_name='tblrelordenservicioarticulos',
            name='art_cantidad',
            field=models.SmallIntegerField(verbose_name='Cantidad:'),
        ),
        migrations.AlterField(
            model_name='tblrelordenservicioarticulos',
            name='art_precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio:'),
        ),
    ]
