# Generated by Django 4.1.1 on 2022-10-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CiuNombre', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIdentificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('CliTipoDocumento', models.CharField(choices=[('T.I', 'Tarjeta de Identidad'), ('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('Pas', 'Pasaporte')], default='C.C', max_length=4, verbose_name='Tipo de documento')),
                ('CliNombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('CliApellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('CliGenero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Maculino')], max_length=2)),
                ('CliDireccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('CliTelefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('CliCelular', models.CharField(max_length=20, verbose_name='Celular')),
                ('CliEmail', models.CharField(max_length=100, verbose_name='Email')),
                ('TblCiudades_idCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudades', verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepNombre', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarNombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('MarCategoria', models.CharField(choices=[('Motos', 'Motos'), ('Carro', 'Carro')], max_length=5)),
                ('Marvaloracion', models.CharField(max_length=5, verbose_name='Valoración')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMatricula', models.CharField(max_length=6, verbose_name='Matrícula')),
                ('VehModelo', models.CharField(max_length=45, verbose_name='Modelo')),
                ('VehColor', models.CharField(max_length=20, verbose_name='Color')),
                ('VehVersion', models.CharField(max_length=20, verbose_name='Versión')),
                ('VehAnio', models.DateField(help_text='AAAA', verbose_name='Año')),
                ('VehChasis_VIN', models.CharField(max_length=45, verbose_name='Chasis_VIN')),
                ('VehMotor', models.CharField(max_length=45, verbose_name='Motor')),
                ('VehUltima_Fecha_Ingreso', models.DateField(help_text='MM/DD/AAA', verbose_name='Ultima fecha de ingreso')),
                ('VehUltima_Fecha_Salida', models.DateField(help_text='MM/DD/AAA', verbose_name='Ultima fecha de Salida')),
                ('VehInforme_Tecnico', models.CharField(max_length=200, verbose_name='Informe técnico')),
                ('TblCliente_idIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Dueño')),
                ('TblMarcas_idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.marcas', verbose_name='Marca')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='TblDepartamento_idDepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.departamentos', verbose_name='Departamento'),
        ),
    ]
