# Generated by Django 4.1.1 on 2022-10-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudades',
            name='CiuEstado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='idCiudad',
            field=models.CharField(default=0, max_length=10, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='CliEstado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='DepEstado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='idDepart',
            field=models.CharField(default=0, max_length=10, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marcas',
            name='MarEstado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='VehEstado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
