# Generated by Django 4.1.1 on 2022-10-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_ciudades_ciuestado_ciudades_idciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='idCiudad',
            field=models.CharField(max_length=10, verbose_name='Código nacional'),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='idDepart',
            field=models.CharField(max_length=10, verbose_name='Código nacional'),
        ),
    ]
