# Generated by Django 4.1.1 on 2022-10-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_ciudades_idciudad_alter_departamentos_iddepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CliTelefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idIdentificacion',
            field=models.CharField(max_length=50, verbose_name='Identificación:'),
        ),
    ]
