# Generated by Django 4.1.2 on 2022-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_clitelefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CliEmail',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
