# Generated by Django 4.1.2 on 2022-10-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_cliemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='VehInforme_Tecnico',
            field=models.TextField(max_length=200, verbose_name='Informe técnico'),
        ),
    ]
