# Generated by Django 4.1.2 on 2022-10-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_vehiculo_vehinforme_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='VehAnio',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='VehUltima_Fecha_Ingreso',
            field=models.DateField(verbose_name='Ultima fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='VehUltima_Fecha_Salida',
            field=models.DateField(verbose_name='Ultima fecha de Salida'),
        ),
    ]
