# Generated by Django 4.1.2 on 2022-10-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_alter_articulos_artstockdisp_and_more'),
        ('clientes', '0007_alter_vehiculo_vehanio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='TblMarcas_idMarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.marcas', verbose_name='Marca'),
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
    ]
