# Generated by Django 4.1.2 on 2022-10-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_vehiculo_tblmarcas_idmarca_delete_marcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='VehTaller',
            field=models.CharField(choices=[('Si', 'En taller'), ('No', 'Entregado')], default='Si', max_length=2, verbose_name='Proceso:'),
        ),
    ]
